### ISSUE TITLE
500 Error when posting topic

### ISSUE THREAD

**Issue by Shawn-James** [Lambda-School-Labs/Labs26-Apollo-iOS-TeamA#22]
`TopicController.postTopic()` gives a 500 error. It's being called from [here](https://github.com/Lambda-School-Labs/Labs26-Apollo-iOS-TeamA/blob/fcc4fae3021f8a97b3f748753a032140a047f6b9/labs-ios-starter/Surveys/View%20Controllers/TopicQuestionsViewController.swift#L98)

**Comment by froggomad** [comment]
Resolved by removing `id` property from encode method on Topic model
